# Generated by Django 3.2.4 on 2021-07-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogTitle', models.CharField(default='', max_length=100)),
                ('heading', models.CharField(default='', max_length=500)),
                ('headingContent', models.CharField(default='', max_length=5000)),
                ('subHeading0', models.CharField(default='', max_length=500)),
                ('subHeading0Content', models.CharField(default='', max_length=5000)),
                ('subHeading1', models.CharField(default='', max_length=500)),
                ('subHeading1Content', models.CharField(default='', max_length=5000)),
                ('postDate', models.DateField()),
                ('postThumbnail', models.ImageField(default='', upload_to='blog/img')),
            ],
        ),
    ]
