# Generated by Django 3.2.4 on 2021-07-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_contact_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemsJson', models.CharField(max_length=100000)),
                ('customerName', models.CharField(max_length=100)),
                ('customerEmail', models.CharField(max_length=200)),
                ('customerPhone', models.IntegerField()),
                ('customerAddress', models.CharField(max_length=400)),
                ('customerCity', models.CharField(max_length=100)),
                ('customerState', models.CharField(max_length=100)),
                ('customerZipCode', models.CharField(max_length=10)),
                ('orderDate', models.DateTimeField()),
            ],
        ),
    ]
