# Generated by Django 3.2.4 on 2021-07-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='updateTimeStamp',
            field=models.DateTimeField(),
        ),
    ]
